# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 7.3

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --configuration phpunit.xml